source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

def common_target
    # react + react-native
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTCameraRoll',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTLinkingIOS',
    ]
    # react third-party module
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    # react-navigation
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    # others
    pod 'react-native-camera', :path => '../node_modules/react-native-camera'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'RNLocalize', :path => '../node_modules/react-native-localize/ios'
    pod 'RNSound', :path => '../node_modules/react-native-sound'
    pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
end

target "Easemob" do
    common_target
    pod 'react-native-im-easemob', :podspec => '../node_modules/react-native-im-easemob/react-native-im-easemob.podspec'
    pod 'Hyphenate', '= 3.5.1'
    pod 'MJExtension', :git => 'https://github.com/hecom-rn/MJExtension.git', :commit => 'cd3de71c4955935a762a46e59d90160991f5fa92'
end
